<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/11/27
 * Time: 下午8:57
 */
namespace app\common\lib\exception;

use Exception;
use think\exception\Handle;
//异常处理类
class ApiHandleException extends Handle {
   public function render(Exception $e)
   {
       if (config('app_debug')) {
           return parent::render($e); // TODO: Change the autogenerated stub
       }
       $httpCode = 500;
       $status = -1;

       if ($e instanceof ApiException) {
           $httpCode = $e->httpCode;
           $status = $e->status;
       }
       return show($status,$e->getMessage(),[],$httpCode);
   }

}