<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/12/4
 * Time: 下午4:03
 */
namespace app\api\controller\v1;

use app\api\controller\Common;
use app\common\lib\exception\ApiException;
use app\common\lib\OpenSSLAES;

//后台进行验证token值
class LoginBase extends Common
{
    //定义属性 在下次获取用户信息的时候可以直接调用
    public $user;

    //初始化
    public function _initialize()
    {
        $this->isLogin();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function isLogin()
    {
        //获取系统级的请求参数access_token
        $access_token = request()->header()['access_token'];

        //验证access_token是否存在 不存在就是第一次登陆
        if (!$access_token) {
            throw new ApiException('access_token不存在', 400, 3008);
        }

        //相反,access_token存在,用第三方OpenSSLAES里的decrypt()进行解密
        //new OpenSSLAES实例化这个类
         $openSSLAES = new OpenSSLAES(config('app.aes_key'));
        $access_token= $openSSLAES->decrypt($access_token);
        //list()把数组中的值赋值给变量
        list($token,$id) = explode('||',$access_token);
        $user = model('User')->where(['id'=>$id])->find();
        if ($user['token'] != $token) {
            throw new ApiException('token值错误',401,3009);
        }
        if (time() > $user['token_time']) {
            throw new ApiException('token超时', 401, 3010);
        }

    }

}